### ISSUE TITLE
# det_layers

### ISSUE THREAD

**Issue by 1358422654** [MohsenZand/ObjectBox#13]
# det_layers
det_layers:
  - [8,8, 16,16, 32,32, 64,64, 128,128]  # P3/8
  - [8,8, 16,16, 32,32, 64,64, 128,128]  # P4/16
  - [8,8, 16,16, 32,32, 64,64, 128,128]  # P5/32
  
For P3,P4 and P5, why are they the same size for objects of different sizes? Can I directly replace it with anchors below? Will it affect the accuracy and speed?

anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

**Comment by MohsenZand** [comment]
They are constant scale gains, as explained on page 7 of the paper. They cannot be replaced by anchors, since they are interpreted differently.

**Comment by 1358422654** [comment]
Thank you very much for your reply。
