### ISSUE TITLE
Questions about S part of SDIOU

### ISSUE THREAD

**Issue by 0phoff** [MohsenZand/ObjectBox#17]
Hey,
Thanks for your inspiring work, it is quite refreshing to see a new take on object detection.

I had a question about the formulation of the **S** part of your [loss function](https://github.com/MohsenZand/ObjectBox/blob/abf47a26bafb577565ec4bbaaa1e8f595deca051/loss.py#L210).
According to Fig 4 in your article, the non-overlapping area S is equal to the two blue boxes.
However, looking at your formula `S = (L* - L)² + (T* - T)² + (R* - R)² + (B* - B)²`, it seems to visually be rather equal to 4 red boxes below.
It seems your formulation is based on the [scaled balanced loss paper](https://ieeexplore.ieee.org/document/9112187), but could you explain the reason for this squared distance in more details ?

<img src="https://user-images.githubusercontent.com/11853089/199561995-bec15093-dca9-41af-a02c-df926f5616d3.png" width=300 /> ![non-overlapping-area](https://user-images.githubusercontent.com/11853089/199561626-75d5dd46-fa36-462c-9eb8-bb9c528416f0.svg)

**Comment by MohsenZand** [comment]
Thank you!
What you have shown is literally the same as below:

![Untitled](https://user-images.githubusercontent.com/60530783/202924956-145f7cc1-0cf0-4326-9896-7b87742eff4b.png)

S = [(L* - L)² + (B* - B)²]+ [(T* - T)² + (R* - R)²], where [(L* - L)² + (B* - B)²] and [(T* - T)² + (R* - R)²] denote the square of diagonal of red rectangles A and B, respectively. 
As similar to scale balanced loss paper, we use the squared Euclidean distance to measure the distance between different points. We however show the area of the rectangles in the figure to make it more intuitive.

**Comment by 0phoff** [comment]
Ok, that's what I figured after reading the scale balanced loss paper, but thanks for clearing this out! :)

**Comment by xiaobai111111223** [comment]
Can this loss function be used directly in FCOS?
