### ISSUE TITLE
some issues about ObjectBox

### ISSUE THREAD

**Issue by Antonwxb** [MohsenZand/ObjectBox#21]
HELLO,
I'm really interested in your brilliant work but i still got a few questions:
1. What if (the predicted L^(i) + the predicted R^(i))<1? OR (the predicted T^(i) + the predicted B^(i))<1. In that case the predicted{L T R B} can't form a rectangle bounding box. (And I think it's possible because the predicted{L T R B} are only set to be greater than 0)
2. I can't understand why the predicted box will have at least one joint point with the bounding box. Just like the picture below, the predicted black box has no joint area with the GT box and it stassify the limitation that the predicted {L T R B}>0.  
![image](https://user-images.githubusercontent.com/115979887/204866133-1d505f64-4b2a-4564-b878-03f1e5834bc0.png)

Since I'm just a beginner in this field and I haven't carefully read the relased code yet, so if I made any stupid mistake or missed something mentioned in the paper, please point out and let me know. Thank you.

**Comment by MohsenZand** [comment]
Thank you!
The predictions are assigned to the cells. For each cell x, (L,T,R,B) are relative distances from x to the boundaries of the bounding box. An example of the worst case (where the predicted and ground-truth boxes share only one point) is shown below: 

![Screenshot 2022-12-03 232611](https://user-images.githubusercontent.com/60530783/205474467-373d4ea9-7857-4fdc-b5d2-cb7f0d0eeeb4.png)

**Comment by Antonwxb** [comment]
As you stated in the paper, the L(i)* + R(i)* = w(i) + 1(formula (1)). Thus the L(i)* + R(i)* must be greater than 1. But according to formula(2), the predicted (L T R B) are only set to be greater than 0. So I think the predicted L(i) + R(i) might be smaller than 1. Will this inconsistency cause any problems?  Or the (L* T* R* B*) in formula(1) and the (L T R B) in formula(2) are not exactly equivalent ?

**Comment by MohsenZand** [comment]
It simply indicates that the sum of L and R at each scale is 1 unit more than the bounding box width. Additionally, individual L,T,R, or B >= 0. They don't appear to be contradictory.

**Comment by Antonwxb** [comment]
Thank you very much! ALL THE BEST !!!

**Comment by Antonwxb** [comment]
Sorry to bother you again, but after I simply read the code , I still can't figure out this question:
If the predicted (L T R B) is like this (i.e. L+R<1, B+T<1), then where is the predicted bounding box ?
![image](https://user-images.githubusercontent.com/115979887/206203073-d3f739b0-591f-4227-8863-af8c9374b6c9.png)

**Comment by MohsenZand** [comment]
The cell size is one unit in each scale. Because L+R = W +1 (and B+T = H + 1), your case never occurs.

**Comment by Antonwxb** [comment]
Why? I think only the ground truth (L* T* R* B*) satisfy the constraint that L*+R*=W+1 and B*+T*=H+1, the predicted (L T R B) are only set to be greater than 0 according to the paper. If both predicted L and predicted R are really small (smaller than 0.5), than this case occurs.

**Comment by Antonwxb** [comment]
I think this problem is exist. Maybe you can try to fix this issue and present a more perfect model. Thank you for your patience and ,best wishes!
