### ISSUE TITLE
AttributeError: 'Detect' object has no attribute 'det_layers_grid'

### ISSUE THREAD

**Issue by Murray-Yin** [MohsenZand/ObjectBox#22]
Thanks for your sharing! 
There is an issue about "AttributeError: 'Detect' object has no attribute 'det_layers_grid'" when I run the val.py.
I try my hard to locate the problem, e.g., the detail can be seen in the followed figure. 
Could you help me to figure out this problem?
Thanks again! 
![image](https://user-images.githubusercontent.com/114552554/205444964-ccfeb73d-1eee-488d-97e7-b71623dbd2e2.png)

**Comment by MohsenZand** [comment]
Thank you!
Please uncomment line 60.

**Comment by Murray-Yin** [comment]
> Thank you! Please uncomment line 60.

Nice! Thanks! 
Oh, by the way, I am studying the mmdetection recently, and I want to know if your ObjectBox has the mmdetection version?
Happy Sunday!

**Comment by MohsenZand** [comment]
Unfortunately, not yet. 
And you too, thank you!
