### ISSUE TITLE
what' s the meaning of the SDIOU

### ISSUE THREAD

**Issue by qiuhaining** [MohsenZand/ObjectBox#5]
I: the square of the length of the diagonal of intersection area
s: the sum of the square of the length of the diagonal of non-overlap area
c: the square of the length of the diagonal of smallest covering area

but:

SDIOU=(I-S)/C
what' s the meaning of the SDIOU???  expain it please， thank you！

**Comment by MohsenZand** [comment]
It stands for scale-invariant distance-based IoU. You can find more details in the paper Sec. 3.2.

**Comment by qiuhaining** [comment]
收到了！谢谢！
