### ISSUE TITLE
network output

### ISSUE THREAD

**Issue by zqing10** [MohsenZand/ObjectBox#9]
Hi, Thanks for your great work.
what' s the meaning of '3' in the size of network output?expain it please， thank you
![微信图片_20220901150304](https://user-images.githubusercontent.com/62885530/187852523-eb7038ee-503d-47da-8fa4-15a7c243b865.jpg)

**Comment by MohsenZand** [comment]
Thank you for noticing this.
This is a typo and must be 1.
